# Generated by Django 2.2.1 on 2019-05-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20190520_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-id',)},
        ),
    ]
